#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Super
hc keybind $Mod-Pause quit
hc keybind $Mod-Insert reload

# tags
TAG_NAMES=( A Z E R Q S D {1..5} )
TAG_KEYS=( a z e r q s d F{1..5} )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-i split horizontal 0.76
hc keybind $Mod-t floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-Escape close_or_remove

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
#hc keybind $Mod-a jumpto urgent

hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# colors
#hc set frame_border_active_color '#222222'
#hc set frame_border_normal_color '#101010'
#hc set frame_bg_normal_color '#565656'
#hc set frame_bg_active_color '#345F0C'
#hc set window_border_normal_color '#454545'
#hc set window_border_active_color '#9fbc00'


# rules
hc unrule -F

hc rule focus=on

hc rule class~'[Tt]rayer' manage=off

hc rule class~'mednafen' pseudotile=on
hc rule class~'StepMania' pseudotile=on
hc rule class~'milkytracker' pseudotile=on
hc rule class~'obs' pseudotile=on
hc rule class~'Wine' pseudotile=on
hc rule class~'FLTK' title~'butt' pseudotile=on
hc rule class~'Chrome' windowrole~'pop-up' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_SPLASH' pseudotile=on
hc rule class~'uplink.*' pseudotile=on
hc rule class~'superhexagon.*' pseudotile=on
hc rule title~'Rebirth Item Tracker' pseudotile=on

herbstclient set tree_style '╾│ ├└╼─┐'

hc detect_monitors

hc set auto_detect_monitors 1
hc set focus_follows_mouse 1
hc set swap_monitors_to_get_tag 1

hc set frame_border_width 0
hc set frame_gap 6
hc set frame_padding 0
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 0
hc set window_border_inner_width 0
hc set window_border_width 1
hc set window_gap -1

hc set mouse_recenter_gap 5

hc set always_show_frame 0

hc set focus_stealing_prevention 0

#default colours
 MOST="#f66"
 MORE="#668"
   FG="#888"
 LESS="#aaa"
LEAST="#bbb"
   BG="#d8d8d8"

#system-specific
COLORS=$( dirname $0 )/$( hostname -s ).colors.sh
if [[ -f $COLORS ]]; then
  source $COLORS
fi

hc set window_border_active_color $MORE
hc set window_border_normal_color $BG
hc set window_border_urgent_color $MOST

hc set frame_normal_opacity 100
hc set frame_active_opacity 33
hc set frame_bg_normal_color $BG
hc set frame_bg_active_color black

hc set default_frame_layout 2

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

# unlock, just to be sure
hc unlock
